// Generated by CoffeeScript 1.7.1
var fs, http, io, server, socket, socketFile;

http = require('http');

io = require('socket.io');

fs = require('fs');

socketFile = fs.readFileSync(__dirname + '/socketio.html');

server = http.createServer();

server.on('request', function(req, res) {
  res.writeHead('200', {
    'content-type': 'text/html'
  });
  return res.end(socketFile);
});

server.listen(9090);

socket = io.listen(server);

socket.on('connection', function(client) {
  console.log('Client connected');
  return client.send("Welcome " + client.sessionId);
});
